# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pseudo', models.CharField(max_length=20)),
                ('mdp', models.CharField(max_length=50)),
                ('niveau', models.IntegerField()),
                ('adr', models.EmailField(max_length=40)),
                ('master', models.BooleanField()),
            ],
        ),
    ]
