# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0002_joueur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joueur',
            old_name='adr',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='joueur',
            old_name='niveau',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='joueur',
            old_name='mdp',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='joueur',
            old_name='Pseudo',
            new_name='pseudo',
        ),
    ]
