# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Enigmes', '0003_auto_20170307_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joueur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='joueur',
            name='password',
        ),
        migrations.RemoveField(
            model_name='joueur',
            name='pseudo',
        ),
        migrations.AddField(
            model_name='joueur',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
